//This file is automatically generated by build_number.cmake

#ifndef __BUILD_NUMBER_H__INCLUDED__
#define __BUILD_NUMBER_H__INCLUDED__

#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_PATCH 2402
#define VERSION_BUILD 1324
#define VERSION_STRING "1.2.2402.1324"

#endif