//This file is automatically generated by build_number.cmake

#ifndef __BUILD_NUMBER_H__INCLUDED__
#define __BUILD_NUMBER_H__INCLUDED__

#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_PATCH 2310
#define VERSION_BUILD 1031
#define VERSION_STRING "1.2.2310.1031"

#endif